Repository zio/zio, pull requests merged in 2019-06, with the labels that each got.

#967 Remove leftovers from Travis->Circle migration
  CONTRIBUTING.md
  project/secrets.tar.xz.enc
  project/travis-deploy-key.pub
Labels: organization

#997 Coerce mdoc into thinking we are using Travis
  .circleci/config.yml
Labels: build, documentation

#1031 Fix confusion between fatal() and withNonFatal()
  core/shared/src/main/scala/zio/Runtime.scala
  core/shared/src/main/scala/zio/internal/Platform.scala
Labels: bug

#1019 DRY the build
  .circleci/config.yml
  project/ScalazBuild.scala
Labels: build

#1050 Fix release errors
  .circleci/config.yml
  project/ScalazBuild.scala
Labels: build

#1068 Fix node and yarn related issues for publishing microsite via circleci
  .circleci/config.yml
  .nvmrc
  website/package.json
Labels: build

#1067 Fix broken links in contributing docs
  CONTRIBUTING.md
Labels: documentation

#1064 Added circleci step to compile dotty
  .circleci/config.yml
  build.sbt
Labels: build, dotty
