Repository zio/zio, pull requests merged in 2020-01, with the labels that each got.

#2624 Add algolia search to microsite
  website/siteConfig.js
Labels: documentation

#2623 Combine Lint and Fix Checks in CI
  .circleci/config.yml
Labels: build

#2727 ZIO: Enable snapshot releases
  .circleci/config.yml
  .scala-steward.conf
  build.sbt
  project/plugins.sbt
Labels: WIP, build

#2728 Add snapshots to badge bar of README
  README.md
Labels: documentation

#2730 Add codeowners for build
  .github/CODEOWNERS
Labels: build
