Repository zio/zio, pull requests merged in 2020-11, with the labels that each got.

#4373 Update sbt-ci-release to 1.5.4
  project/plugins.sbt
Labels: dependency-update

#4369 Update sbt to 1.4.2
  project/build.properties
  scalafix/project/build.properties
Labels: dependency-update

#4375 Update sbt-mdoc to 2.2.11
  project/plugins.sbt
Labels: dependency-update

#4377 Update sbt-scalafix to 0.9.23
  project/plugins.sbt
  scalafix/project/plugins.sbt
Labels: dependency-update

#4378 Update zio-interop-reactivestreams to 1.3.0.7-2
  build.sbt
Labels: dependency-update

#4379 Update sbt-bloop to 1.4.5
  project/plugins.sbt
Labels: dependency-update

#4390 Update fs2-core to 2.4.5
  build.sbt
Labels: dependency-update

#4382 Update scalacheck to 1.15.1
  build.sbt
Labels: dependency-update

#4401 Update sbt-dotty to 0.4.6
  project/plugins.sbt
Labels: dependency-update

#4394 Update mdoc, sbt-mdoc to 2.2.12
  project/plugins.sbt
Labels: dependency-update

#4408 Update sbt to 1.4.3
  project/build.properties
  scalafix/project/build.properties
Labels: dependency-update

#4411 Update organize-imports to 0.4.4
  project/BuildHelper.scala
Labels: dependency-update

#4407 Update zio-interop-twitter to 20.10.0.0
  build.sbt
Labels: dependency-update

#4405 Update sbt-scalajs, scalajs-compiler, ... to 1.3.1
  project/plugins.sbt
Labels: dependency-update

#4413 Update hedgehog-core to 0.6.0
  build.sbt
Labels: dependency-update

#4424 Update scaluzzi to 0.1.16
  project/BuildHelper.scala
Labels: dependency-update

#4439 Update sbt to 1.4.4
  project/build.properties
  scalafix/project/build.properties
Labels: dependency-update

#4437 Improve TSemaphore
  core/shared/src/main/scala/zio/stm/TSemaphore.scala
  project/MimaSettings.scala
Labels: performance, stm

#4444 Update fs2-core to 2.4.6
  build.sbt
Labels: dependency-update

#4453 Update mdoc-js, sbt-mdoc to 2.2.13
  project/plugins.sbt
Labels: dependency-update

#4458 Fix refineOrDie implementation
  streams-tests/shared/src/test/scala/zio/stream/ZStreamSpec.scala
  streams/shared/src/main/scala/zio/stream/ZStream.scala
Labels: stream

#4464 Update cats-effect to 2.3.0
  build.sbt
Labels: dependency-update

#4468 Update wagon-http to 3.4.2
  build.sbt
Labels: dependency-update
