Repository zio/zio, pull requests merged in 2021-04, with the labels that each got.

#4869 Require mdoc for mergify
  .github/workflows/site.yml
  .mergify.yml
Labels: build

#4873 Update refined to 0.9.23
  build.sbt
Labels: dependency-update

#4876 Update maven-compat, maven-embedder to 3.8.1
  build.sbt
Labels: dependency-update

#4877 Update sbt to 1.5.0
  project/build.properties
  scalafix/project/build.properties
Labels: dependency-update

#4879 Update scala-java-time, ... to 2.2.1
  build.sbt
Labels: dependency-update

#4881 Up our CI game
  .github/release-drafter.yml
  .github/renovate.json
  .github/workflows/ci.yml
  .mergify.yml
  build.sbt
  project/BuildHelper.scala
  project/plugins.sbt
Labels: build

#4907 Update akka-stream to 2.6.14
  build.sbt
Labels: type: dependencies

#4932 Update izumi-reflect to 1.0.0
  build.sbt
Labels: type: dependencies

#4933 Update izumi-reflect to 1.1.0
  build.sbt
Labels: type: dependencies

#4950 Update zio-interop-reactivestreams to 1.3.2
  build.sbt
Labels: type: dependencies

#4953 Update reactor-core to 3.4.5
  build.sbt
Labels: type: dependencies

#4977 Update zio-interop-reactivestreams to 1.3.3
  build.sbt
Labels: type: dependencies

#4981 Update snakeyaml-engine to 2.3
  project/plugins.sbt
Labels: type: dependencies

#4989 Update cats-effect to 2.5.0
  build.sbt
Labels: type: dependencies

#4990 Update mdoc-js, sbt-mdoc to 2.2.20
  project/plugins.sbt
Labels: type: dependencies

#4994 Update zio-interop-cats to 2.4.1.0
  build.sbt
Labels: type: dependencies

#4998 Update refined to 0.9.24
  build.sbt
Labels: type: dependencies

#5000 Update scala-java-time, ... to 2.2.2
  build.sbt
Labels: type: dependencies

#5011 Update fs2-core to 2.5.5
  build.sbt
Labels: type: dependencies

#5012 Update hedgehog-core to 0.6.6
  build.sbt
Labels: type: dependencies

#5021 Update sbt to 1.5.1
  project/build.properties
  scalafix/project/build.properties
Labels: type: dependencies

#5025 Update zio-interop-reactivestreams to 1.3.4
  build.sbt
Labels: type: dependencies

#5028 Update util-core to 21.4.0
  build.sbt
Labels: type: dependencies
